### ISSUE TITLE
Model update

### ISSUE THREAD

**Issue by jamsun9907** [jamsun9907/Recipe_recommendation#3]
#### To-do
| 작업 완성까지 달려 🔥
- [ ] Countvectorizer(binary=True) 로 수정
- [ ] 불용어처리
- [ ] 오직 재료가 다 있는 레시피만 추천 받을래요 버전추가
- [ ] 사용자가 무조건 있을 재료 제거하기

#### Big update
- [ ] cloud DB 연결(실시간 레시피 추출)
- [ ] [프론트엔드] 사용자 입력값 저장
- [ ] 사용자 입력값 DB 저장
- [ ] 위의 내용은 오라클로 cloud 및 DB 구현
